VERSION: 2
MODEL:
  # WEIGHTS: "training_dir/BoxInst/Base-BoxInst3D/model_0009999.pth"
  # WEIGHTS: "training_dir/BoxInst/Base-BoxInst3D_2/model_0000029.pth"
  META_ARCHITECTURE: "CondInst3D"
  MASK_ON: True
  PIXEL_MEAN: [None]
  BACKBONE:
    NAME: "build_unet3d"
  PROPOSAL_GENERATOR:
    NAME: "MaskHead"
  UNET3D:
    OUT_FEATURES: ['p1','p2','p3','p4','p5']
  MASKHEAD:
    NUM_CLASSES: 1
  # FCOS:
  #   IN_FEATURES: ['p1']
  #   FPN_STRIDES: [1]
  #   NUM_CLASSES: 2
  #   THRESH_WITH_CTR: True
  #   USE_SCALE: True
  CONDINST:
    TOPK_PROPOSALS_PER_IM: 64
    MASK_OUT_STRIDE: 1
    MASK_BRANCH:
      OUT_CHANNELS: 8
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 0
    PAIRWISE:
      SIZE: 3
      DILATION: 2
      COLOR_THRESH: 0.3
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  GAMMA: 0.1
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  STEPS: (250, 280)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 50
  WARMUP_METHOD: 'linear'
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: None
  WEIGHT_DECAY_NORM: 0.0
  MAX_ITER: 300
  CHECKPOINT_PERIOD: 5
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: BGR
