VERSION: 2
MODEL:
  META_ARCHITECTURE: "CondInst3D"
  MASK_ON: True
  PIXEL_MEAN: [None]
  BACKBONE:
    NAME: "build_unet3d"
  PROPOSAL_GENERATOR:
    NAME: "MaskHead"
  UNET3D:
    OUT_FEATURES: ['p1','p2','p3','p4','p5']
  MASKHEAD:
    NUM_CLASSES: 1
  # FCOS:
  #   IN_FEATURES: ['p1']
  #   FPN_STRIDES: [1]
  #   NUM_CLASSES: 2
  #   THRESH_WITH_CTR: True
  #   USE_SCALE: True
  CONDINST:
    TOPK_PROPOSALS_PER_IM: 64
    MASK_OUT_STRIDE: 1
    MASK_BRANCH:
      OUT_CHANNELS: 8
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 0
    PAIRWISE:
      SIZE: 3
      DILATION: 2
      COLOR_THRESH: 0.3
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: BGR
