OUTPUT_DIR: training_dir/BoxInst/Base-BoxInst_80
MODEL:
  # WEIGHTS: 'training_dir/BoxInst/Base-BoxInst_tmp/model_0044999.pth'
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_1image/model_0044999.pth"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_1sample/model_0044999.pth"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrained/model_0011999.pth"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrain_100/model_0004999.pth"
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_10tight/model_0009999.pth'
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrain_10tight/model_0010999.pth'
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrain_100tight/model_0013499.pth'
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_100tight/model_0010999.pth'
  # WEIGHTS: training_dir/BoxInst/Base-BoxInst_80/model_0009999.pth 
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    TOP_LEVELS: 2
    FPN_STRIDES: [4,8,16,32,64] # [8, 16, 32, 64, 128]
    SIZES_OF_INTEREST: [32, 64, 128, 256]
    IN_FEATURES: [ 'p2', 'p3', 'p4', 'p5', 'p6']
    THRESH_WITH_CTR: True
    USE_SCALE: True
    NUM_CLASSES: 1
  CONDINST:
    MASK_OUT_STRIDE: 1
    TOPK_PROPOSALS_PER_IM: 64
    MASK_BRANCH:
      OUT_CHANNELS: 16
      IN_FEATURES: ['p2', 'p3', 'p4']
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 0
    PAIRWISE:
      SIZE: 3
      DILATION: 2
      COLOR_THRESH: 0.93
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (60000, 80000)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 500
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
