MODEL:
  # WEIGHTS: 'training_dir/BoxInst/Base-BoxInst_tmp/model_0044999.pth'
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_1image/model_0044999.pth"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_1sample/model_0044999.pth"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrained/model_0011999.pth"
  # WEIGHTS: "/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrain_100/model_0004999.pth"
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_10tight/model_0009999.pth'
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrain_10tight/model_0010999.pth'
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_pretrain_100tight/model_0013499.pth'
  # WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/Base-BoxInst_100tight/model_0010999.pth'
  WEIGHTS: '/home/hynx/AdelaiDet/training_dir/BoxInst/UNet3D-BoxInst_10/model_0016199.pth'
  META_ARCHITECTURE: "UInst3D"
  UINST3D:
    NORMALIZE: False
  PIXEL_MEAN: [None]
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_unet_fpn_backbone"
  UNETD:
    STAGE_NUM: 5
    MAX_CHANNELS: 320
    BASE_CHANNELS: 16
    OUT_FEATURES: ["res2", "res3", "res4"]
  FPN:
    FUSE_TYPE: 'sum'
    IN_FEATURES: ["res2", "res3", "res4"]
    NORM: ''
    OUT_CHANNELS: 128
  PROPOSAL_GENERATOR:
    NAME: "FCOS3D"
  FCOS:
    TOP_LEVELS: 2
    FPN_STRIDES: [4,8,16,32,64] # [8, 16, 32, 64, 128]
    SIZES_OF_INTEREST: [32, 64, 128, 256]
    IN_FEATURES: [ 'p2', 'p3', 'p4', 'p5', 'p6']
    THRESH_WITH_CTR: False
    INFERENCE_TH_TEST: 0.015
    USE_SCALE: True
    NUM_CLASSES: 1
  CONDINST:
    MASK_OUT_STRIDE: 2
    TOPK_PROPOSALS_PER_IM: 64
    MASK_BRANCH:
      OUT_CHANNELS: 16
      IN_FEATURES: ['p2', 'p3', 'p4']
    MASK_HEAD: 
      CHANNELS: 8
      DISABLE_REL_COORDS: False
      NUM_LAYERS: 3 
      USE_FP16: False
  BOXINST:
    ENABLED: True
    BOTTOM_PIXELS_REMOVED: 0
    PAIRWISE:
      SIZE: 3
      DILATION: 1
      COLOR_THRESH: 0.93
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  STEPS: (20000, 25000)
  WARMUP_FACTOR: 0.001
  WARMUP_ITERS: 300
  WARMUP_METHOD: 'linear'
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: None
  WEIGHT_DECAY_NORM: 0.0
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 100
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
